{% set name = "playwright-python" %}
{% set version = "1.50.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Microsoft/playwright-python/archive/v{{ version }}.tar.gz
  sha256: 6b9820cc2680902bd6140e05c47dffba234a252d2118d5d22512a2140a4d1905
  patches:
    - auditwheel.patch  # auditwheel is only available for linux, so we remove it from the build requirements
    - setup.patch       # Disable download of binaries 
    - driver.patch      # Fix playwright nodejs location

build:
  entry_points:
    - playwright=playwright.__main__:main
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools =68.2.2
    - setuptools-scm =8.0.4
    - wheel =0.42.0
    - pip
  run:
    - python >={{ python_min }}
    - greenlet =3.1.1
    - pyee =12.0.0
    - playwright

test:
  imports:
    - playwright
  commands:
    - pip check
    - playwright install --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Microsoft/playwright-python
  summary: Python version of the Playwright testing and automation library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
