{% set name = "playwright-python" %}
{% set version = "1.45.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Microsoft/playwright-python/archive/v{{ version }}.tar.gz
  sha256: 1fa139980bb4531539791713c636a102843257df08ded24a88b6ba3ceb78e16e
  patches:
    - auditwheel.patch  # auditwheel is only available for linux, so we remove it from the build requirements
    - setup.patch       # Disable download of binaries 
    - driver.patch      # Fix playwright nodejs location

build:
  entry_points:
    - playwright=playwright.__main__:main
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools ==68.2.2
    - setuptools-scm ==8.0.4
    - wheel ==0.42.0
    - pip
  run:
    - python >=3.8
    - greenlet ==3.0.3
    - pyee ==11.1.0
    - playwright

test:
  imports:
    - playwright
  commands:
    - pip check
    - playwright install --help
  requires:
    - pip

about:
  home: https://github.com/Microsoft/playwright-python
  summary: Python version of the Playwright testing and automation library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
